[JENKINS-41306] Migrate to 2.x parent POM. Fix javadoc issues.
jenkinsci/icon-shim-plugin pull request #4
Opened 2017-01-23 08:12 UTC by varyvol

[JENKINS-41306](https://issues.jenkins-ci.org/browse/JENKINS-41306)

- Migrate to 2.x parent POM.
- Fix some Javadoc issues.
- Fix some Findbugs issues.

@reviewbybees @tfennelly

2017-01-24 07:40 UTC, kwhetstone commented
🐝

2017-02-03 14:39 UTC, andresrc approved these changes
:bee:

2017-02-03 14:47 UTC, andresrc requested changes

2017-02-03 14:47 UTC, andresrc commented on pom.xml
>        <plugin>
* The version for the `maven-release-plugin` can be obtained from the parent pom
* Change `http` to `https` in the repositories.

2017-02-06 08:33 UTC, varyvol commented
@andresrc changes done.

2017-02-09 10:51 UTC, varyvol commented
@jglick I think you have also put some work on this plugin, so your review would be much appreciated.

2017-02-24 14:14 UTC, andresrc approved these changes

2017-02-24 14:15 UTC, andresrc commented
@tfennelly @jglick ok to merge and release this?

2017-02-25 13:08 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-03-03 09:17 UTC, tfennelly commented on icon-set/src/main/java/org/jenkins/ui/icon/Icon.java
> +import java.io.Serializable;
I don't see any other change relating to this?

2017-03-03 09:17 UTC, tfennelly approved these changes
LGTM 👍

2017-03-03 09:19 UTC, varyvol commented on icon-set/src/main/java/org/jenkins/ui/icon/Icon.java
> +import java.io.Serializable;
The StringComparator implements it.

2017-03-03 09:21 UTC, merged